### PR TITLE
Lab 8022 - EventMesh - TEQ / KAFKA : Repo Migration

### PR DESCRIPTION
**Pull request by pasimoes**
Migrating all project from oracle-db-examples repo to dcms repo.
Target: /microservices-datadriven/workshops/eventmesh-teq-kafka

### CODE REVIEW

**Review by RichardExley — COMMENTED** [review]
I see a lot of code from the package package org.oracle.okafka.common.utils.  What is this?

**Comment by pasimoes** [comment]
> I see a lot of code from the package package org.oracle.okafka.common.utils. What is this?

This is OKAFKA package. Next release of my project it will turn to git module.

**Review by paulparkinson — CHANGES_REQUESTED** [review]
wow, that's a big PR :) . I'll give it another review once it is in but it looks ok and isolated in the workshops dir. Let's just get rid of the .gitignore . If you need to add something please do it in the root .gitignore Thanks.

**Comment by pasimoes** [comment]
@paulparkinson revision done.

**Review by paulparkinson — APPROVED** [review]

**Pull request merged**
