### PR TITLE
Reorg

### PR DESCRIPTION
**Pull request by RichardExley**

### CODE REVIEW

**Review by paulparkinson — DISMISSED** [review]

**Comment by RichardExley** [comment]
Small changes to fix object store based secret store to workaround bug https://github.com/oracle/oci-cli/issues/490

**Comment by RichardExley** [comment]
Fixes for 1DB ATP.

**Comment by RichardExley** [comment]
Tested on Live Labs and Free Trial with Credits

**Comment by renagranat** [comment]
Tested on LiveLabs

**Review by renagranat — APPROVED** [review]

**Pull request merged**
